site_name: Powerful Benchmarker
nav:
    - Home: index.md
    - Command Line Syntax: cl_syntax.md
    - Yaml Syntax: yaml_syntax.md
    - Hyperparameter Optimization: hyperparams.md
    - Modules You Can Access: modules.md
    - Adding Custom Modules: custom.md
    - Default Config File Guide: 
      - config_dataset: configs/config_dataset.md
      - config_eval: configs/config_eval.md
      - config_factories: configs/config_factories.md
      - config_general: configs/config_general.md
      - config_loss_and_miners: configs/config_loss_and_miners.md
      - config_models: configs/config_models.md
      - config_optimizers: configs/config_optimizers.md
      - config_transforms: configs/config_transforms.md
    - Code Documentation:
      - Aggregators: code/aggregators.md
      - API Parsers: code/api_parsers.md
      - Architectures: code/architectures.md
      - Datasets: code/datasets.md
      - Ensembles: code/ensembles.md
      - Factories: code/factories.md
      - Runners: code/runners.md
      - Split Managers: code/split_managers.md
      - Utils: code/utils.md
    - Papers:
      - A Metric Learning Reality Check: papers/mlrc.md
theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'blue'
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - attr_list
repo_name: 'KevinMusgrave/powerful-benchmarker'
repo_url: 'https://github.com/KevinMusgrave/powerful-benchmarker'
extra_css:
  - stylesheets/extra.css